spring.application.name=user-auth

# database configuration
spring.datasource.url=jdbc:mysql://mysql:3306/user_auth
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true